### ISSUE TITLE
How to pass opts to vuetify?

### ISSUE THREAD

**Issue by brunobg** [socheatsok78/storybook-addon-vuetify#1]
Is there a way to pass opts to vuetify, to set theme colors for example? Thank you

**Comment by jozef-rzadkosz** [comment]
Yeah, it's a good question, how can we pass a color pallete to theme or set customVariables or customProperties?

**Comment by socheatsok78** [comment]
Released: [v0.1.9](https://github.com/socheatsok78/storybook-addon-vuetify/releases/tag/v0.1.9)
